name: my_dbt_project
version: '1.0'
profile: my_dbt_project  # This should match the profile name in profiles.yml

source-paths:
  - models

# Optional configurations
models:
  my_dbt_project:
    +materialized: table
